# model
model_name: "seq2seq_rnn"
embed_size: 300
hidden_size: 100
num_layers: 1

#vocab
min_freq: 10

# data
dataset_root: "dataset/ordered"
batch_size: 32
drop_last: False

# training
number_of_epochs: 10
lr: 0.05
criterion: "masked_crossEntropyLoss"
scheduler: "None"
