# model
model_name: "seq2seq_rnn"
embed_size: 300
hidden_size: 100
num_layers: 1

#vocab
min_freq: 10

# data
#root_dir:"drive/MyDrive/seq-seq"
#dataset_root: "drive/MyDrive/seq-seq/copyable_dataset"
root_dir:"."
dataset_root: "dataset/ordered"
batch_size: 32
drop_last: False

# training
is_continue_training: False
number_of_epochs: 10
lr: 0.2
criterion: "masked_crossEntropyLoss"
scheduler: "StepLR"
